all:
  children:
    iosxe:
      children:
        R1:
          hosts:
            192.168.50.61:
        R2:
          hosts:
            192.168.50.62:
    nxos:
      children:
        SW1:
          hosts:
            192.168.50.63

